# Generated by Django 3.2.9 on 2021-11-04 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericmodelforeign',
            name='fourth_engineer',
        ),
        migrations.RemoveField(
            model_name='genericmodelforeign',
            name='third_engineer',
        ),
        migrations.RemoveField(
            model_name='genericmodelmain',
            name='address',
        ),
        migrations.RemoveField(
            model_name='genericmodelmain',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='genericmodelmain',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='genericmodelmain',
            name='position',
        ),
        migrations.AlterField(
            model_name='genericmodelforeign',
            name='engine_cadet',
            field=models.ManyToManyField(default='', related_name='engine_cadet', to='mainapp.GenericModelMain', verbose_name='Engine cadet'),
        ),
        migrations.AlterField(
            model_name='genericmodelforeign',
            name='second_engineer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_engineer', to='mainapp.genericmodelmain', verbose_name='Second engineer'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='birth_date',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='employment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Employment date'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='middle_name',
            field=models.CharField(max_length=254, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='sex',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=254, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 3, 13, 27, 6, 901367, tzinfo=utc), verbose_name='Termination date'),
        ),
    ]
